substitutions:
  name: esp32-c3-ld2410
  friendly_name: ESP32-C3-LD2410
  espID: esp32_c3_ld2410

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: 100
      then:
        lambda: |-
          id(cpu_speed) = ESP.getCpuFreqMHz();
 
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    # Replace with your own
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  # Replace with your own
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}_Fallback_Hotspot
    password: ${name}

captive_portal:

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: '0'

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
  #cache_services: false

debug:
  update_interval: 30s

uart:
  id: ld2410_uart
  tx_pin: GPIO7
  rx_pin: GPIO6
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

number:
  - platform: ld2410
    timeout:
      name: "timeout"
    max_move_distance_gate:
      name: "max move distance gate"
    max_still_distance_gate:
      name: "max still distance gate"
    g0:
      move_threshold:
        name: "g0 move threshold"
      still_threshold:
        name: "g0 still threshold"
    g1:
      move_threshold:
        name: "g1 move threshold"
      still_threshold:
        name: "g1 still threshold"
    g2:
      move_threshold:
        name: "g2 move threshold"
      still_threshold:
        name: "g2 still threshold"
    g3:
      move_threshold:
        name: "g3 move threshold"
      still_threshold:
        name: "g3 still threshold"
    g4:
      move_threshold:
        name: "g4 move threshold"
      still_threshold:
        name: "g4 still threshold"
    g5:
      move_threshold:
        name: "g5 move threshold"
      still_threshold:
        name: "g5 still threshold"
    g6:
      move_threshold:
        name: "g6 move threshold"
      still_threshold:
        name: "g6 still threshold"
    g7:
      move_threshold:
        name: "g7 move threshold"
      still_threshold:
        name: "g7 still threshold"
    g8:
      move_threshold:
        name: "g8 move threshold"
      still_threshold:
        name: "g8 still threshold"
    light_threshold:
      name: "light threshold"

text_sensor:
  - platform: debug
    reset_reason:
      name: "ESP Reset Reason"
      icon: mdi:anchor
      disabled_by_default: True
  - platform: wifi_info
    ip_address:
      name: "ESP IP Address"
    ssid:
      name: "ESP Connected SSID"
    bssid:
      name: "ESP Connected BSSID"
    mac_address:
      name: "ESP Mac Wifi Address"
    scan_results:
      name: "ESP Latest Scan Results"
  - platform: ld2410
    version:
      name: "Presenece Sensor Version"
    mac_address:
      name: "Presenece Sensor Mac Address"

sensor:
  - platform: template
    name: "ESP CPU Speed"
    accuracy_decimals: 0
    icon: mdi:cpu-32-bit
    unit_of_measurement: Mhz
    disabled_by_default: True
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"
    update_interval: 600s
  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 45s
    entity_category: "diagnostic"
  - platform: uptime
    name: ESP Uptime
    id: sys_uptime
    update_interval: 60s
  - platform: wifi_signal 
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"
    update_interval: 60s
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0: 
      move_energy:
        name: "g0 move energy"
      still_energy:
        name: "g0 still energy"
    g1: 
      move_energy:
        name: "g1 move energy"
      still_energy:
        name: "g1 still energy"
    g2: 
      move_energy:
        name: "g2 move energy"
      still_energy:
        name: "g2 still energy"
    g3: 
      move_energy:
        name: "g3 move energy"
      still_energy:
        name: "g3 still energy"
    g4: 
      move_energy:
        name: "g4 move energy"
      still_energy:
        name: "g4 still energy"
    g5: 
      move_energy:
        name: "g5 move energy"
      still_energy:
        name: "g5 still energy"
    g6: 
      move_energy:
        name: "g6 move energy"
      still_energy:
        name: "g6 still energy"
    g7: 
      move_energy:
        name: "g7 move energy"
      still_energy:
        name: "g7 still energy"
    g8: 
      move_energy:
        name: "g8 move energy"
      still_energy:
        name: "g8 still energy"
    light:
      name: "light"

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
    entity_category: diagnostic
  - platform: ld2410
    factory_reset:
      name: "LD2410 Factory Reset"
      entity_category: diagnostic
    restart:
      name: "LD2410 Restart"
      entity_category: config
    query_params:
      name: "LD2410 query params"

switch:
  - platform: ld2410
    engineering_mode:
      name: "LD2410 Engineering Mode"
    bluetooth:
      name: "LD2410 Control Bluetooth"
  - platform: factory_reset
    name: Factory Reset
    disabled_by_default: True
    icon: mdi:heart-broken

select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: "light function"
    out_pin_level:
      name: "out pin level"

binary_sensor:
  - platform: status
    name: "ESP Status"
  - platform: ld2410
    has_target:
      name: "Presence"
    has_moving_target:
      name: "Moving Target"
    has_still_target:
      name: "Still Target"
